# Generated by Django 6.1.1 on 2026-09-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='background_image',
            field=models.ForeignKey(blank=True, help_text="Optional background image shown behind this project's page. Falls back to the site's default background if left blank.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
