# Generated by Django 6.1.1 on 2026-09-20 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectpage_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='background_overlay_opacity',
            field=models.PositiveIntegerField(default=70, help_text='Darkness of the overlay on top of the background image: 0 = full image, no darkening, 100 = fully dark. Only applies when a background image is set.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
