# Generated by Django 6.1.1 on 2026-10-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectpage_background_overlay_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='end_date',
            field=models.DateField(blank=True, help_text='Leave blank if the project is still in development (shown as "Present"). Set it once the project is finished or no longer being worked on.', null=True),
        ),
    ]
