# Generated by Django 6.1.1 on 2026-10-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Shown above the form as a direct way to reach you.', max_length=254),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Full profile URL, e.g. https://www.linkedin.com/in/your-name/', verbose_name='LinkedIn URL'),
        ),
    ]
