# Generated by Django 6.1.1 on 2026-09-15 19:42

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0098_apitoken'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('heading', models.CharField(blank=True, help_text='Big hero heading, e.g. your name.', max_length=255)),
                ('subheading', models.CharField(blank=True, help_text='Short role/title line under the heading.', max_length=255)),
                ('intro', wagtail.fields.RichTextField(blank=True, help_text='A few sentences introducing yourself.')),
                ('resume_document', models.ForeignKey(blank=True, help_text='Optional resume/CV file, linked from the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
