# Generated by Django 6.1.1 on 2026-09-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='aka_name',
            field=models.CharField(blank=True, help_text='Optional "aka" line shown under the heading, e.g. aka "Shashwamie".', max_length=255),
        ),
    ]
