# Generated by Django 6.1.1 on 2026-10-05 05:38

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_homepage_aka_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='flip_cards',
            field=wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Shown on the front of the card.'}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional short line under the title on the front.', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Shown on the back once the card is flipped.'}), 3: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Optional page linked from the back of the card.', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Label for that link, e.g. "See all projects".', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('teaser', 1), ('body', 2), ('link_page', 3), ('link_text', 4)]], {})}, help_text='Cards between the hero and Featured projects that visitors click to flip over.'),
        ),
    ]
