# Generated by Django 6.1.1 on 2026-09-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_timelineevent_options_timelineevent_end_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(choices=[('gaming', 'Gaming'), ('tcg', 'TCG'), ('skiing', 'Skiing'), ('mountain_biking', 'Mountain Biking'), ('legos', 'Legos'), ('rock_climbing', 'Rock Climbing'), ('game_dev', 'Game Development'), ('reading', 'Reading'), ('camping', 'Camping'), ('motorcycles', 'Motorcycles')], max_length=30)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short blurb shown when the card is flipped.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
