# Generated by Django 6.1.1 on 2026-09-28 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_hobby'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobby',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Card art. Leave empty to use a placeholder built from the icon.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
