# Generated by Django 6.1.1 on 2026-10-02 12:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_hobby_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='languages',
            field=wagtail.fields.StreamField([('language', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'icon': 'tag'})}, help_text='One block per language, shown as badges.'),
        ),
    ]
