# Generated by Django 6.1.1 on 2026-10-02 14:09

import json

import wagtail.fields
from django.db import migrations


def _convert(stream, to_struct):
    for block in stream:
        if block.get("type") != "skill":
            continue
        value = block["value"]
        if to_struct and isinstance(value, str):
            block["value"] = {"name": value, "description": ""}
        elif not to_struct and isinstance(value, dict):
            block["value"] = value.get("name", "")
    return stream


def _migrate(apps, to_struct):
    # Skills used to be plain CharBlocks ("python"); they're now StructBlocks
    # ({"name": "python", "description": ""}). Rewrite the stored JSON on the
    # live page and on every revision, so older revisions still load in the
    # admin's history/preview.
    AboutPage = apps.get_model("about", "AboutPage")
    Revision = apps.get_model("wagtailcore", "Revision")
    ContentType = apps.get_model("contenttypes", "ContentType")

    for page in AboutPage.objects.all():
        page.skills = _convert(list(page.skills.raw_data), to_struct)
        page.save(update_fields=["skills"])

    content_type = ContentType.objects.filter(app_label="about", model="aboutpage").first()
    if content_type is None:
        return
    for revision in Revision.objects.filter(content_type=content_type):
        skills = revision.content.get("skills")
        if not skills:
            continue
        stream = json.loads(skills) if isinstance(skills, str) else skills
        stream = _convert(stream, to_struct)
        revision.content["skills"] = json.dumps(stream) if isinstance(skills, str) else stream
        revision.save(update_fields=["content"])


def forwards(apps, schema_editor):
    _migrate(apps, to_struct=True)


def backwards(apps, schema_editor):
    _migrate(apps, to_struct=False)


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutpage_languages'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='skills',
            field=wagtail.fields.StreamField([('skill', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Shown in the panel that opens when the skill is clicked.', 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1)]], {'icon': 'tag'})}, help_text='One block per skill. Each opens a description panel when clicked.'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
